server:
  port: 8080

spring:

  application:
    name: api-gateway

  cloud:

    gateway:

      globalcors:

        cors-configurations:

          '[/**]':

            allowedOrigins: "*"

            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

            allowedHeaders: "*"


      routes:

        # =========================================================
        # Auth Service
        # =========================================================

        - id: auth-service

          uri: lb://AUTH-SERVICE

          predicates:
            - Path=/api/auth/**


        # =========================================================
        # Auth Service Swagger
        # =========================================================

        - id: auth-service-docs

          uri: lb://AUTH-SERVICE

          predicates:
            - Path=/auth-service/v3/api-docs, /auth-service/v3/api-docs/**

          filters:
            - RewritePath=/auth-service/(?<remaining>.*), /$\{remaining}


        # =========================================================
        # Product Service
        # =========================================================

        - id: product-service

          uri: lb://PRODUCT-SERVICE

          predicates:
            - Path=/api/products/**


        # =========================================================
        # Product Service Swagger
        # =========================================================

        - id: product-service-docs

          uri: lb://PRODUCT-SERVICE

          predicates:
            - Path=/product-service/v3/api-docs, /product-service/v3/api-docs/**

          filters:
            - RewritePath=/product-service/(?<remaining>.*), /$\{remaining}


# ===============================================================
# Swagger UI
# ===============================================================

springdoc:

  swagger-ui:

    path: /swagger-ui.html

    urls:

      - name: Auth Service
        url: /auth-service/v3/api-docs

      - name: Product Service
        url: /product-service/v3/api-docs


# ===============================================================
# Eureka
# ===============================================================

eureka:

  client:

    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

    register-with-eureka: true

    fetch-registry: true
