management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - gateway

  endpoint:
    gateway:
      enabled: true
